### ISSUE TITLE
Nuxt 3 Integration

### ISSUE THREAD

**Issue by estnml** [samchon/typia#934] opened 2024-01-19 18:03 UTC
## Question
Hello, i am trying to use this library in nuxt 3 application. I followed the instructions on the webpage, but i am getting an error.

## What i did
1) pnpm install --save typia
2) pnpm install --save-dev typescript ts-patch ts-node
3) added "plugins": [{ "transform": "typia/lib/transform" }] to tsconfig.json
4) added "prepare": "ts-patch install && typia patch" to package.json
5) created templates and generated folders in the root.
6) pnpm typia generate --input templates --output generated --project tsconfig.json
7) modified nuxt.config.ts to auto import .ts files inside templates folder. added -> imports: {dirs: ["types/*.ts", "templates/*.ts"]},
8) Created IRegisterUser interface in the templates folder.
9) run "pnpm run prepare" command
10) Inside the register.vue component:
```vue
const registerData = ref<IRegisterUser>({
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: ""
})

assert<IRegisterUser>(registerData.value);
```
11) When i go to webpage, it does not open and in the console it says "Uncaught (in promise) Error: Error on typia.assert(): no transform has been configured. Read and follow https://typia.io/docs/setup please.".

**Comment by Tenrys** [comment] 2024-04-10 19:27
I tried following steps [over here](https://github.com/samchon/typia/issues/812) as well, and I could not get it to work.

**Comment by ryoppippi** [comment] 2024-06-08 09:46
@estnml @Tenrys 
You can check this out https://typia.io/docs/setup/#unplugin-typia

**Comment by ryoppippi** [comment] 2024-06-08 09:59
also duplicate of https://github.com/samchon/typia/issues/775

**Closed as completed** 2024-06-12 14:29 UTC
Labels: help wanted
